import {
    Loader2,
    Upload,
    File,
    Trash,
    Edit,
    X,
    Plus,
    Check,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    MoreVertical,
    Calendar,
    Clock,
    AlertCircle,
    Download,
} from "lucide-react"

export const Icons = {
    spinner: Loader2,
    upload: Upload,
    file: File,
    trash: Trash,
    edit: Edit,
    close: X,
    add: Plus,
    check: Check,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    chevronDown: ChevronDown,
    more: MoreVertical,
    calendar: Calendar,
    clock: Clock,
    alert: AlertCircle,
    download: Download,
} 